### your site title here

title: Jason R. Singson, MPH
description: Epidemiologist, Researcher, Community Organizer

baseurl: "/" #name of GitHub repository
url: "https://multimodal.github.io" #custom url to be used instead of GitHub repository
email: %22Jason%20Singson%22%3cstub-inrush.0x@icloud.com%3e?Inquiry from Github Site
#%22John%20Wayne%22%3cjw@email.com%3e?subject..
# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter: "@multimodal_epi"
linkedin: "jrcsingson"
### stackoverflow: "#"
github: "multimodal-epi"
researchgate: "Jason-Robert-Singson-2"
orcid: "0000-0002-9113-1190"
### quora: "#"
instagram: "multimodal_epi"
### facebook: "#"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
